baseurl = "https://username.github.io"
DefaultContentLanguage = "en"
title = "DDD Melbourne"
metaDataFormat = "yaml"
#googleAnalytics = "XXX"

[Params]
  subtitle = "DDD Melbourne is a non profit community event run by developers for developers. Anyone can submit a session to the event and delegates then vote on the sessions they want to see."
  favicon = "img/favicon.ico"
  dateFormat = "Mon Jan 2, 2006"
  showDddByNight = true

[Author]
  name = "DDD Melbourne"
  email = "dddmelbourne@gmail.com"
  github = "OpenDDD"
  twitter = "dddmelb"
  instagram = "dddmelb"
  flickr = "photos/92981424@N05/albums/72157634918888979"

[[menu.main]]
    name = "Blog"
    url = "https://blog.dddmelbourne.com/"
    weight = 6
